<a href="https://colab.research.google.com/github/KeshavaOfficial/keshav/blob/Projects/Recomeddation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
anime_df = pd.read_csv('/content/anime.csv')

In [ ]:

anime_df = anime_df.sort_values(by='anime_id').reset_index(drop=True)
anime_df

,anime_id,name,genre,type,episodes,rating,members
0,1,Cowboy Bebop,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",TV,26,8.82,486824
1,5,Cowboy Bebop: Tengoku no Tobira,"Action, Drama, Mystery, Sci-Fi, Space",Movie,1,8.40,137636
2,6,Trigun,"Action, Comedy, Sci-Fi",TV,26,8.32,283069
3,7,Witch Hunter Robin,"Action, Drama, Magic, Mystery, Police, Superna...",TV,26,7.36,64905
4,8,Beet the Vandel Buster,"Adventure, Fantasy, Shounen, Supernatural",TV,52,7.06,9848
...,...,...,...,...,...,...,...
12289,34514,Pokemon Generations,"Action, Adventure, Fantasy, Game, Kids",ONA,18,7.21,295
12290,34519,Mobile Suit Gakuen: G-Reco Koushien,Comedy,Special,9,5.67,94
12291,34522,"Wake Up, Girls! Shin Shou","Drama, Music",TV,Unknown,NaN,381
12292,34525,Centaur no Nayami,"Comedy, Fantasy, Slice of Life, Supernatural",TV,Unknown,NaN,108
12293,34527,Gou-chan. Moko to Chinjuu no Mori no Nakama-tachi,"Adventure, Kids",Movie,1,NaN,5

In [ ]:
anime_df.head()

,anime_id,name,genre,type,episodes,rating,members
0,1,Cowboy Bebop,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",TV,26,8.82,486824
1,5,Cowboy Bebop: Tengoku no Tobira,"Action, Drama, Mystery, Sci-Fi, Space",Movie,1,8.40,137636
2,6,Trigun,"Action, Comedy, Sci-Fi",TV,26,8.32,283069
3,7,Witch Hunter Robin,"Action, Drama, Magic, Mystery, Police, Superna...",TV,26,7.36,64905
4,8,Beet the Vandel Buster,"Adventure, Fantasy, Shounen, Supernatural",TV,52,7.06,9848

In [ ]:
anime_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12294 entries, 0 to 12293
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   anime_id  12294 non-null  int64
 1   name      12294 non-null  object
 2   genre     12232 non-null  object
 3   type      12269 non-null  object
 4   episodes  12294 non-null  object
 5   rating    12064 non-null  float64
 6   members   12294 non-null  int64
dtypes: float64(1), int64(2), object(4)
memory usage: 672.5+ KB

In [ ]:
anime_df.describe()

           anime_id        rating       members
count  12294.000000  12064.000000  1.229400e+04
mean   14058.221653      6.473902  1.807134e+04
std    11455.294701      1.026746  5.482068e+04
min        1.000000      1.670000  5.000000e+00
25%     3484.250000      5.880000  2.250000e+02
50%    10260.500000      6.570000  1.550000e+03
75%    24794.500000      7.180000  9.437000e+03
max    34527.000000     10.000000  1.013917e+06

In [ ]:
len(anime_df.anime_id.unique())

12294

In [ ]:
len(anime_df.name.unique())

12292

In [ ]:
user_anime_df = anime_df.pivot(index = 'anime_id', columns = 'name', values = 'rating').reset_index()

In [ ]:
user_anime_df

name,anime_id,&quot;0&quot;,"&quot;Aesop&quot; no Ohanashi yori: Ushi to Kaeru, Yokubatta Inu",&quot;Bungaku Shoujo&quot; Kyou no Oyatsu: Hatsukoi,&quot;Bungaku Shoujo&quot; Memoire,&quot;Bungaku Shoujo&quot; Movie,&quot;Eiji&quot;,&quot;Eiyuu&quot; Kaitai,.hack//G.U. Returner,.hack//G.U. Trilogy,...,s.CRY.ed,vivi,xxxHOLiC,xxxHOLiC Kei,xxxHOLiC Movie: Manatsu no Yoru no Yume,xxxHOLiC Rou,xxxHOLiC Shunmuki,Üks Uks,ēlDLIVE,◯
0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12289,34514,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12290,34519,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12291,34522,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12292,34525,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12293,34527,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
user_anime_df.fillna(0, inplace = True)

In [ ]:
user_anime_df

name,anime_id,&quot;0&quot;,"&quot;Aesop&quot; no Ohanashi yori: Ushi to Kaeru, Yokubatta Inu",&quot;Bungaku Shoujo&quot; Kyou no Oyatsu: Hatsukoi,&quot;Bungaku Shoujo&quot; Memoire,&quot;Bungaku Shoujo&quot; Movie,&quot;Eiji&quot;,&quot;Eiyuu&quot; Kaitai,.hack//G.U. Returner,.hack//G.U. Trilogy,...,s.CRY.ed,vivi,xxxHOLiC,xxxHOLiC Kei,xxxHOLiC Movie: Manatsu no Yoru no Yume,xxxHOLiC Rou,xxxHOLiC Shunmuki,Üks Uks,ēlDLIVE,◯
0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12289,34514,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12290,34519,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12291,34522,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12292,34525,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12293,34527,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
from sklearn.metrics import pairwise_distances

In [ ]:
user_sim =  1 - pairwise_distances( user_anime_df.values,metric='cosine')

In [ ]:
user_sim

array([[0.        , 0.05762219, 0.06589538, ..., 0.11265691, 0.11265691,
        0.11265691],
       [0.05762219, 0.        , 0.29917761, ..., 0.51148386, 0.51148386,
        0.51148386],
       [0.06589538, 0.29917761, 0.        , ..., 0.58492091, 0.58492091,
        0.58492091],
       ...,
       [0.11265691, 0.51148386, 0.58492091, ..., 0.        , 1.        ,
        1.        ],
       [0.11265691, 0.51148386, 0.58492091, ..., 1.        , 0.        ,
        1.        ],
       [0.11265691, 0.51148386, 0.58492091, ..., 1.        , 1.        ,
        0.        ]])

In [ ]:
user_sim_df = pd.DataFrame(user_sim)

In [ ]:
user_sim_df.index = anime_df.anime_id.unique()
user_sim_df.columns = anime_df.anime_id.unique()

In [ ]:
user_sim_df.iloc[0:5, 0:5]

          1         5         6         7         8
1  0.000000  0.057622  0.065895  0.077639  0.084468
5  0.057622  0.000000  0.299178  0.352496  0.383502
6  0.065895  0.299178  0.000000  0.403106  0.438564
7  0.077639  0.352496  0.403106  0.000000  0.516723
8  0.084468  0.383502  0.438564  0.516723  0.000000

In [ ]:
np.fill_diagonal(user_sim, 0)
user_sim_df.iloc[0:5, 0:5]

          1         5         6         7         8
1  0.000000  0.057622  0.065895  0.077639  0.084468
5  0.057622  0.000000  0.299178  0.352496  0.383502
6  0.065895  0.299178  0.000000  0.403106  0.438564
7  0.077639  0.352496  0.403106  0.000000  0.516723
8  0.084468  0.383502  0.438564  0.516723  0.000000

In [ ]:

user_sim_df.idxmax(axis=1)[0:5]

1    3786
5    3786
6    3786
7    3786
8    3786
dtype: int64

In [ ]:
anime_df[(anime_df['anime_id']==1) | (anime_df['anime_id']==5)]

,anime_id,name,genre,type,episodes,rating,members
0,1,Cowboy Bebop,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",TV,26,8.82,486824
1,5,Cowboy Bebop: Tengoku no Tobira,"Action, Drama, Mystery, Sci-Fi, Space",Movie,1,8.40,137636

In [ ]:
user_1 = anime_df[anime_df['anime_id']==1]

In [ ]:
user_2=anime_df[anime_df['anime_id']==5]

In [ ]:
anime_df.columns

Index(['anime_id', 'name', 'genre', 'type', 'episodes', 'rating', 'members'], dtype='object')

In [ ]:
user_1.name

0    Cowboy Bebop
Name: name, dtype: object

In [ ]:
user_2.name

1    Cowboy Bebop: Tengoku no Tobira
Name: name, dtype: object

In [ ]:
pd.merge(user_1,user_2,on='name',how='outer')

,anime_id_x,name,genre_x,type_x,episodes_x,rating_x,members_x,anime_id_y,genre_y,type_y,episodes_y,rating_y,members_y
0,1.0,Cowboy Bebop,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",TV,26,8.82,486824.0,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Cowboy Bebop: Tengoku no Tobira,NaN,NaN,NaN,NaN,NaN,5.0,"Action, Drama, Mystery, Sci-Fi, Space",Movie,1,8.4,137636.0

In [ ]:
cowboybebop_user_rating = user_anime_df['Cowboy Bebop']

In [ ]:
cowboybebop_user_rating.iloc[0:11]

0     8.82
1     0.00
2     0.00
3     0.00
4     0.00
5     0.00
6     0.00
7     0.00
8     0.00
9     0.00
10    0.00
Name: Cowboy Bebop, dtype: float64

In [ ]:
similar_to_cowboy = user_anime_df.corrwith(cowboybebop_user_rating)

In [ ]:
similar_to_cowboy.head(10)

name
anime_id                                                           -0.011068
&quot;0&quot;                                                      -0.000081
&quot;Aesop&quot; no Ohanashi yori: Ushi to Kaeru, Yokubatta Inu   -0.000081
&quot;Bungaku Shoujo&quot; Kyou no Oyatsu: Hatsukoi                -0.000081
&quot;Bungaku Shoujo&quot; Memoire                                 -0.000081
&quot;Bungaku Shoujo&quot; Movie                                   -0.000081
&quot;Eiji&quot;                                                   -0.000081
&quot;Eiyuu&quot; Kaitai                                           -0.000081
.hack//G.U. Returner                                               -0.000081
.hack//G.U. Trilogy                                                -0.000081
dtype: float64

In [ ]:
corr_cowboy = pd.DataFrame(similar_to_cowboy, columns=['Correlation'])
corr_cowboy.dropna(inplace=True)
corr_cowboy.head()

                                                    Correlation
name
anime_id                                              -0.011068
&quot;0&quot;                                         -0.000081
&quot;Aesop&quot; no Ohanashi yori: Ushi to Kae...    -0.000081
&quot;Bungaku Shoujo&quot; Kyou no Oyatsu: Hats...    -0.000081
&quot;Bungaku Shoujo&quot; Memoire                    -0.000081

In [ ]:
corr_cowboy[corr_cowboy['Correlation'] > 0].sort_values(by='Correlation', ascending=False).head(5)

              Correlation
name
Cowboy Bebop          1.0

#Training Data

In [ ]:
x = anime_df.iloc[:, 0:5]

In [ ]:
x.head()

,anime_id,name,genre,type,episodes
0,1,Cowboy Bebop,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",TV,26
1,5,Cowboy Bebop: Tengoku no Tobira,"Action, Drama, Mystery, Sci-Fi, Space",Movie,1
2,6,Trigun,"Action, Comedy, Sci-Fi",TV,26
3,7,Witch Hunter Robin,"Action, Drama, Magic, Mystery, Police, Superna...",TV,26
4,8,Beet the Vandel Buster,"Adventure, Fantasy, Shounen, Supernatural",TV,52

In [ ]:
y = anime_df.iloc[:, 5]

In [ ]:
y.head()

0    8.82
1    8.40
2    8.32
3    7.36
4    7.06
Name: rating, dtype: float64

In [ ]:
from sklearn.model_selection import train_test_split
x_test,x_train,y_test,y_train = train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:

print(f"Training set size: {x_train.shape}")
print(f"Testing set size: {x_test.shape}")

print(f"Training set size: {y_train.shape}")
print(f"Testing set size: {y_test.shape}")

Training set size: (2459, 5)
Testing set size: (9835, 5)
Training set size: (2459,)
Testing set size: (9835,)

In [ ]:
from sklearn.metrics import precision_score, recall_score, f1_score
import numpy as np

# Assuming `similar_to_cowboy` contains actual relevant recommendations (1 = relevant, 0 = not relevant)
# Assuming `cowboybebop_user_rating` contains predicted recommendations

# Convert to 1D binary lists
actual = np.array(similar_to_cowboy.iloc[:, 0:5]).flatten()  # Flatten into 1D array
predicted = np.array(cowboybebop_user_rating.iloc[:, 0:5]).flatten()

# Ensure binary values (0 or 1)
actual = np.where(actual > 0, 1, 0)  # Convert to binary (1 if relevant, 0 otherwise)
predicted = np.where(predicted > 0, 1, 0)

# Compute evaluation metrics
precision = precision_score(actual, predicted, zero_division=0)
recall = recall_score(actual, predicted, zero_division=0)
f1 = f1_score(actual, predicted, zero_division=0)

print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-Score: {f1:.4f}")

#Difference Between User-Based and Item-Based Collaborative Filtering
User-Based Collaborative Filtering finds users with similar preferences and recommends items liked by those similar users.

It works by calculating similarity between users using metrics like cosine similarity or Pearson correlation.

Struggles with the cold start problem when new users have little data.

Item-Based Collaborative Filtering finds items that are similar and recommends them to users based on past interactions.

It is more stable than user-based filtering, as item preferences don’t change frequently.

# What is Collaborative Filtering and How Does It Work?
Collaborative Filtering is a recommendation technique that predicts user preferences by analyzing behavior patterns of similar users.

It works by collecting user-item interactions, computing similarity scores, and recommending items based on this data.

Can be Memory-Based (using similarity measures) or Model-Based (using ML techniques like Matrix Factorization).

Struggles with the cold start problem when there is limited data for new users/items.

Used in recommendation systems like Netflix, Amazon, and Spotify to suggest relevant content.